# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dcstt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_0b2d3b37d8444aad83d9c8dce7199718 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bde4440a31c84dfea95e1358eecabf66 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0b2d3b37d8444aad83d9c8dce7199718 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dcstt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d6191b07a084bfc8b3780107408a3fa }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0b2d3b37d8444aad83d9c8dce7199718 }}/appsvc/staticsite:${{ github.sha }}'